spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
          fetch_size: 100
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
          jdbc:
            lob:
              non_contextual_creation: true
    datasource:
        url: jdbc:postgresql://localhost:5432/cake_database?useSSL=false&serverTimezone=UTC
        username: postgres
        password: 123456789
        driver-class-name: org.postgresql.Driver
